apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test
spec:
  selector:
    matchLabels:
      run: flask-test
  replicas: 2
  template:
    metadata:
      labels:
        run: flask-test
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000  # Specify the UID of a non-root user
      imagePullSecrets:
      - name: regcred
      containers:
      - name: flask-test
        image: cohenaj194/flask-test
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: http-lb-flask
spec:
  selector:
    run: flask-test
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer

