apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test
spec:
  selector:
    matchLabels:
      run: flask-test
  replicas: 2
  template:
    metadata:
      labels:
        run: flask-test
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000  # Specify the UID of a non-root user
      imagePullSecrets:
      - name: regcred
      containers:
      - name: flask-test
        image: cohenaj194/flask-test
        ports:
        - containerPort: 5000
        # Datadog APM
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
          value: "production"
        - name: DD_SERVICE
          value: "flask-test"
        - name: DD_VERSION
          value: "1.0"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_PROFILING_ENABLED
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: http-lb-flask
spec:
  selector:
    run: flask-test
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer

