resources:
- name: temp-repo
  type: git
  source:
    uri: https://github.com/alexcoderabbitai/temp-fe.git
    branch: main # Track only the main branch
    skip_ssl_verification: true # Use if you have SSL issues, otherwise omit

jobs:
- name: run-semgrep
  plan:
  - get: temp-repo
    trigger: true
  - task: semgrep-scan
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: python
          tag: "3.9" # Use a Python image to install Semgrep
      inputs:
      - name: temp-repo
      outputs:
      - name: semgrep-results # Save results for later use
      run:
        path: sh
        args:
        - -c
        - |
          echo "Installing Semgrep..."
          pip install semgrep
          echo "Running Semgrep scan..."
          cd temp-repo
          semgrep ci --config p/security-audit --config p/owasp-top-ten --config p/javascript --config p/python
          echo "Semgrep scan completed!"
