resources:
  - name: temp-fe-repo
    type: git
    source:
      uri: https://github.com/alexcoderabbitai/temp-fe
      branch: master

jobs:
  - name: semgrep-pr-analysis
    plan:
      - get: temp-fe-repo
        trigger: true  # This triggers the job on any changes (e.g., PRs)

      - task: run-semgrep
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: returntocorp/semgrep
              tag: latest
          run:
            path: semgrep
            args:
              - ci
              - --config
              - "${SEMGREP_RULES}"
              - --path
              - repo
        input_mapping:
          repo: temp-fe-repo
        params:
          SEMGREP_RULES: "p/security-audit p/owasp-top-ten p/javascript p/python"  # Semgrep rules to use
          COMMAND: "ci"  # Run Semgrep in CI mode