name: Auto Comment on PR

on:
  # pull_request:
  #   types: [*]  # Triggers on all pull request events
  pull_request:
    types: [opened]

  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # - name: trigger pr
      #   uses: peter-evans/create-or-update-comment@v4
      #   with:
      #     issue-number: ${{ github.event.pull_request.number }}
      #     body: |
      #       @coderabbitai full review
      - name: trigger pr
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @coderabbitai sing me a song
      - name: Wait 100 sec for timeout
        run: sleep 100
