---
name: Linters

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  "Bandit":
    runs-on: ubuntu-latest
    container: python:3.11

    steps:
      - uses: actions/checkout@v2

      - name: Bandit check
        uses: jpetrucciani/bandit-check@master
        with:
          path: "app.py"
          bandit_flags: "-lll"

      - name: Enable Bandit problem matcher
        run: echo "::add-matcher::$(python -m bandit -m .github/bandit-matcher.json)"

  "Black":
    runs-on: ubuntu-latest
    container: python:3.11

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install black

      - name: Run black check
        run: black --check .

      - name: Add Black problem matcher
        run: echo "::add-matcher::$(pwd)/.github/black-matcher.json"