---
name: Linters

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  Black:
    runs-on: ubuntu-latest
    container: python:3.11

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install black

      - name: Create annotation with file diff
        run: |
          black --diff . | tee diff_output.txt
          echo "::error::Black found code style issues. See the diff below:"
          cat diff_output.txt

      # Run black check and ensure it exits with failure if needed
      - name: Run black check
        run: black --check .