---
name: Linters

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # TODO: Fix Bandit Vulns
  "Bandit":
    runs-on: ubuntu-latest
    container: python:3.11

    steps:
      - uses: actions/checkout@v2

      - name: Bandit check
        uses: jpetrucciani/bandit-check@master
        with:
          path: "app.py"
          bandit_flags: "-lll"

  "Black":
    runs-on: ubuntu-latest
    container: python:3.11

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install black

      - name: Run black check
        run: black --check .
