name: Restart temp-fe Deployment on Staging

# Defines when the workflow should run
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

# Defines the jobs to run
jobs:
  restart-deployment:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1 # Sets up kubectl CLI
      with:
        version: 'v1.20.0' # Specify the version of kubectl you want to use

    - name: Configure Kubeconfig
      env:
        KUBECONFIG_STAGING: ${{ secrets.KUBECONFIG_STAGING }} # Uses the secret encoded in base64
      run: |
        echo "$KUBECONFIG_STAGING" | base64 -d > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Rollout Restart Deployment
      run: kubectl rollout restart deployment flask-test --kubeconfig kubeconfig
